name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1 # Fetching only the latest commit


      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'  # Uses .NET version currently working


      - name: Install dependencies
        run: |
          dotnet restore


      - name: Build the project
        run: |
          dotnet build --configuration Release


      - name: Run tests
        run: |
          dotnet test --configuration Release


      - name: Build Docker image
        run: |
          docker build -t  .  # Replace (blank) with DockerHub username


      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Push Docker image
        run: |
          docker push (X):latest # Replace (X) with DockerHub username
          