name: Run Unit Tests on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1 # Fetching only the latest commit


      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'  # Uses .NET version currently working


      - name: Restore dependencies
        run: |
          dotnet restore


      - name: Run Unit tests
        run: |
          dotnet test --configuration Release
          